/**
 * Writes each gallery page's frame, and each finished job page's, into lib/generated/gallery-shells.js, for
 * api/gallery.js to fill with photographs. Run by build-pages.js after the
 * asset stamping, and stamped the same way, so the frame asks for the same
 * versions of the stylesheets and scripts as every other page.
 *
 * A module rather than a file in public/, because a function cannot rely on
 * reading public/ at run time, and an import is traced into its bundle.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { SITES } from './area-template.js';
import { galleries } from '../content/gallery.js';
import { render, ITEMS_MARKER } from './gallery-template.js';
import { assetHashes, stampAssets } from './asset-version.js';
import { render as renderJob, TOKENS } from './job-template.js';
import { regions } from '../content/regions/index.js';
import { areas } from '../content/areas/index.js';

export async function writeGalleryShells(root) {
  const hashes = await assetHashes(root);
  const shells = {};
  const jobShells = {};
  for (const key of Object.keys(SITES)) {
    if (!SITES[key].galleryPath || !galleries[key]) continue;
    shells[key] = stampAssets(render(key), hashes);
    jobShells[key] = stampAssets(renderJob(key), hashes);
  }
  /* Where a finished job links to: the regional page its postcode area falls
     in. Generated here because a function cannot read content/ at run time. */
  const regionLinks = {};
  for (const r of regions) {
    if (!r.postcodes) continue;
    (regionLinks[r.site] = regionLinks[r.site] || []).push({ name: r.name, href: `${SITES[r.site].areasPath}/${r.slug}`, postcodes: r.postcodes });
  }
  /* The districts each brand has a written area page for, which Insights
     compares the enquiries against to suggest the pages to write next. */
  const areaDistricts = {};
  for (const a of areas) areaDistricts[a.site] = [...new Set([...(areaDistricts[a.site] || []), ...a.districts])].sort();
  const body = `/* Generated by scripts/build-pages.js from scripts/gallery-template.js.
   Edit those, not this file: npm run build:pages rewrites it. */
export const MARKER = ${JSON.stringify(ITEMS_MARKER)};
export const shells = ${JSON.stringify(shells, null, 2)};
export const JOB_TOKENS = ${JSON.stringify(TOKENS)};
export const jobShells = ${JSON.stringify(jobShells, null, 2)};
export const regionLinks = ${JSON.stringify(regionLinks, null, 2)};
export const areaDistricts = ${JSON.stringify(areaDistricts)};
`;
  await mkdir(join(root, 'lib', 'generated'), { recursive: true });
  await writeFile(join(root, 'lib', 'generated', 'gallery-shells.js'), body, 'utf8');
  return Object.keys(shells).length;
}
