/**
 * Writes each gallery page's frame into lib/generated/gallery-shells.js, for
 * api/gallery.js to fill with photographs. Run by build-pages.js after the
 * asset stamping, and stamped the same way, so the frame asks for the same
 * versions of the stylesheets and scripts as every other page.
 *
 * A module rather than a file in public/, because a function cannot rely on
 * reading public/ at run time, and an import is traced into its bundle.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { SITES } from './area-template.js';
import { galleries } from '../content/gallery.js';
import { render, ITEMS_MARKER } from './gallery-template.js';
import { assetHashes, stampAssets } from './asset-version.js';

export async function writeGalleryShells(root) {
  const hashes = await assetHashes(root);
  const shells = {};
  for (const key of Object.keys(SITES)) {
    if (!SITES[key].galleryPath || !galleries[key]) continue;
    shells[key] = stampAssets(render(key), hashes);
  }
  const body = `/* Generated by scripts/build-pages.js from scripts/gallery-template.js.
   Edit those, not this file: npm run build:pages rewrites it. */
export const MARKER = ${JSON.stringify(ITEMS_MARKER)};
export const shells = ${JSON.stringify(shells, null, 2)};
`;
  await mkdir(join(root, 'lib', 'generated'), { recursive: true });
  await writeFile(join(root, 'lib', 'generated', 'gallery-shells.js'), body, 'utf8');
  return Object.keys(shells).length;
}
