/**
 * The sitemaps, one per brand, written by scripts/build-pages.js.
 *
 * Generated rather than kept by hand, so adding a page cannot leave one that
 * nothing links to and nothing lists. Moved out of build-pages.js to keep that
 * file to a readable length.
 */
import { writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { areas } from '../content/areas/index.js';
import { services } from '../content/services/index.js';
import { guides } from '../content/guides/index.js';
import { regions } from '../content/regions/index.js';
import { pricing } from '../content/pricing.js';
import { SITES } from './area-template.js';

export function sitemapFor(site, today) {
  const brand = SITES[site];
  const origin = brand.origin;
  const urls = [
    { loc: `${origin}/`, priority: '1.0', changefreq: 'monthly' },
    { loc: `${origin}/services`, priority: '0.9', changefreq: 'monthly' },
    /* Only what this brand actually serves. Listing a URL nothing answers asks
       Google to crawl a 404 and tells it the site is not looked after. */
    ...(brand.areasPath ? [{ loc: `${origin}${brand.areasPath}`, priority: '0.9', changefreq: 'monthly' }] : []),
    ...(pricing[site] ? [{ loc: `${origin}/pricing`, priority: '0.9', changefreq: 'monthly' }] : []),
    ...(brand.galleryPath ? [{ loc: `${origin}${brand.galleryPath}`, priority: '0.7', changefreq: 'weekly' }] : []),
    { loc: `${origin}/guides`, priority: '0.8', changefreq: 'monthly' },
    ...guides
      .filter((g) => g.site === site)
      .map((g) => ({ loc: `${origin}/guides/${g.slug}`, priority: '0.8', changefreq: 'monthly' })),
    ...services
      .filter((s) => s.site === site)
      .map((s) => ({ loc: `${origin}/services/${s.slug}`, priority: '0.9', changefreq: 'monthly' })),
    ...[...areas, ...regions]
      .filter((a) => a.site === site)
      .map((a) => ({ loc: `${origin}${brand.areasPath}/${a.slug}`, priority: '0.8', changefreq: 'monthly' }))
  ];
  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/build-pages.js. Edit content/, not this file. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.map((u) => `  <url>
    <loc>${u.loc}</loc>
    <lastmod>${today}</lastmod>
    <changefreq>${u.changefreq}</changefreq>
    <priority>${u.priority}</priority>
  </url>`).join('\n')}
</urlset>
`;
}

export async function writeSitemaps(ROOT) {
  // One date for the whole build, taken once, so a run cannot straddle midnight
  // and stamp two different days across the two files.
  const today = new Date().toISOString().slice(0, 10);
  for (const [key, brand] of Object.entries(SITES)) {
    await writeFile(join(ROOT, 'public', brand.sitemapFile), sitemapFor(key, today), 'utf8');
  }
}
